language: vim

os:
  - linux
  - osx

env:
  - TRAVIS_BUILD_DIR="$HOME/.dotfiles"

before_script: |
  # if [ "$TEST" = "package" ]; then
  #   if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  #     sudo apt-get -y update
  #     sudo apt-get -y install vim
  #   fi
  # else
  #   cd ..
  #   git clone --depth 1 https://github.com/vim/vim
  #   cd vim
  #   ./configure --with-features=huge
  #   make
  #   sudo make install
  #   export PATH="/usr/local/bin:$PATH"
  #   cd "$TRAVIS_BUILD_DIR"
  # fi
  # if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  #   curl https://bootstrap.pypa.io/get-pip.py | sudo python
  # fi
  # sudo -H pip install virtualenv
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo apt-get -y update
    sudo apt-get -y install tree vim zsh tmux
  else
    # brew update 
    brew install tree vim zsh tmux
  fi
  git clone https://github.com/buduboti/dotfiles.git $TRAVIS_BUILD_DIR

script:
  - cd $TRAVIS_BUILD_DIR && ls -la && sudo ./install.sh < ./input.txt
