language: vim

os:
  - linux
  - osx

env:
  - TRAVIS_BUILD_DIR="$HOME/.dotfiles"

before_script: |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo apt-get -y update
    sudo apt-get -y install tree vim zsh tmux
  else
    # brew update 
    brew install tree vim zsh tmux
  fi
  git clone -b travis https://github.com/buduboti/dotfiles.git $TRAVIS_BUILD_DIR

script:
  - cd $TRAVIS_BUILD_DIR && ls -la && sudo ./install.sh < ./input.txt
