#!/bin/bash

VERSION=0

if [ "$1" = "kali" -o "$1" = "minimal" ];
then
	VERSION=1
fi

# Install requirements

if [ -f '/usr/bin/apt' ]; then
	sudo apt update 
	sudo apt upgrade 
	sudo apt install -y tmux
	sudo apt install -y vim
	if [ $VERSION -lt 1 ];
	then
		sudo apt install -y curl
		sudo apt install -y zsh
		sudo apt install -y python3
		sudo apt install -y npm
		sudo apt install -y zplug
	fi

	export LANGUAGE=en_US.UTF-8
	export LANG=en_US.UTF-8
	export LC_ALL=en_US.UTF-8
	sudo locale-gen en_US.UTF-8

elif [ -f '/usr/bin/pacman' ]; then
	sudo pacman -Syu 
	sudo pacman -Syy 
	sudo pacman -Sy tmux
	sudo pacman -Sy vim
	if [ $VERSION -lt 1 ];
	then
		sudo pacman -Sy curl
		sudo pacman -Sy zsh
		sudo pacman -Sy python3
		sudo pacman -Sy npm
		sudo pacman -Sy zplug
	fi

elif [ -f '/opt/homebrew/bin/brew' ]; then
	brew install tmux neovim
	if [ $VERSION -lt 1 ];
	then
		brew install curl zsh jq fzf python3 npm zplug
	fi
else
	echo -e "Not found supported package manager...\nTried: apt, pacman, brew.\n"
	exit 127
fi

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

chmod 755 ~/.dotfiles/links.sh && ~/.dotfiles/links.sh

# Clone the theme repo
git submodule update --init --recursive

if [ $VERSION -lt 1 ];
then
	# Clone the theme repo
	git submodule add https://github.com/chriskempson/base16-shell.git ~/.dotfiles/themes/base16-shell/
	 # Apply the theme (there is a lot)
	chmod 755 ~/.dotfiles/themes/base16-shell/scripts/base16-gruvbox-dark-soft.sh && ~/.dotfiles/themes/base16-shell/scripts/base16-gruvbox-dark-soft.sh
	chmod 755 ~/.dotfiles/themes/base16-shell/scripts/base16-gruvbox-light-soft.sh
	# Git
	echo "Your full name [Balás Botond Barna]: "
	read name
	if [ -z $name ]
	then
		git config --global user.name "Balás Botond Barna"
	else
		git config --global user.name "$name"
	fi

	echo "Your email address [buduboti@yahoo.com]: "
	read email
	if [ -z $email ]
	then
		git config --global user.email "buduboti@yahoo.com"
	else
		git config --global user.email "$email"
	fi

	git config --global core.editor vim
fi

# Zsh

# git submodule add https://github.com/zsh-users/zsh-autosuggestions ~/.dotfiles/zsh/plugins/zsh-autosuggestions
# git submodule add https://github.com/zsh-users/zsh-syntax-highlighting ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting 
# git submodule add https://github.com/b4b4r07/enhancd ~/.dotfiles/zsh/plugins/enhancd

# Change the default shell
# echo "password for chsh:"
# chsh -s /bin/zsh

# Vim

echo | (vim +PlugInstall +qall)
# echo | (vim +LspInstall vimls +qall)
# 
# npm install -g typescript-language-server
# npm install -g bash-language-server
# npm install -g typescript
# npm install -g pyright
# 
# python3 -m pip install --user --upgrade python-language-server
# python3 -m pip install --user --upgrade pycodestyle
# python3 -m pip install --user --upgrade pyflakes
# python3 -m pip install --user --upgrade autopep8
# 
# brew install ccls
# 
# python3 -m pip install --user --upgrade pynvim

