
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh

export PATH=$PATH":/Users/buduboti/go/bin:/Users/buduboti/.dotfiles/bin"

# Set theme
~/.dotfiles/themes/base16-shell/scripts/base16-gruvbox-dark-pale.sh
# Prompt
source "$ZSH/prompt.zsh"
# Aliases
source "$ZSH/aliases.zsh"
# Git completion
# $ZSH/git-completion.zsh
# University configs
# source "$ZSH/univ.zsh"

autoload -U compinit
compinit
