export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
export HISTSIZE=9999999
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh
export EDITOR="vim"

# zplug
if [ -d '/opt/homebrew' ]; then
	export ZPLUG_HOME=/opt/homebrew/opt/zplug
else
	export ZPLUG_HOME=/usr/local/opt/zplug
fi
source $ZPLUG_HOME/init.zsh

export HACKS="/Users/buduboti/Documents/hacks"

# include paths in "$DOTFILES/zsh/path" to the PATH
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:/opt/homebrew/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/usr/local/Cellar/*/*/bin"
export PATH="$PATH:/Users/buduboti/Library/Python/3.8/bin"
export PATH="$PATH:/usr/local/opt/llvm/bin"
export PATH="$PATH:/Users/buduboti/Documents/hacks/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/Users/buduboti/Library/Python/3.9/bin"
export PATH="$PATH:$HACKS/bin"

source $DOTFILES/zsh/keybindings.zsh
source $DOTFILES/zsh/async.zsh
source $DOTFILES/zsh/utils.zsh


# Set theme
DARKTHEME="$DOTFILES/themes/base16-shell/scripts/base16-gruvbox-dark-soft.sh"
LIGHTTHEME="$DOTFILES/themes/base16-shell/scripts/base16-gruvbox-light-soft.sh"

$DARKTHEME

dark() {
	$DARKTHEME
}

light() {
	$LIGHTTHEME
}

# # Prompt
source "$ZSH/prompt.zsh"

# Aliases
source "$ZSH/aliases.zsh"

autoload -U compinit
compinit

autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# SmartCase completion

zstyle ':completion:*'  matcher-list 'm:{a-z}={A-Z}'

# $DOTFILES/bin/updater

if [[ "$EUID" == "0" ]]; then
	echo "Hi root!"
else
	echo "Hi $USER!"
fi

# $DOTFILES/bin/updater

